vim.g.loaded_perl_provider = 0

require("jailbreak.plugins-setup")
require("jailbreak.core.options")
require("jailbreak.core.keymaps")
require("jailbreak.core.colorscheme")
require("jailbreak.plugins.comment")
require("jailbreak.plugins.nvim-tree")
require("jailbreak.plugins.lualine")
require("jailbreak.plugins.telescope")
require("jailbreak.plugins.nvim-cmp")
require("jailbreak.plugins.lsp.mason")
require("jailbreak.plugins.lsp.lspsaga")
require("jailbreak.plugins.lsp.lspconfig")
require("jailbreak.plugins.autopairs")
require("jailbreak.plugins.treesitter")
require("jailbreak.plugins.gitsigns")
